package com.sybinal.shop.model;

import java.util.ArrayList;
import java.util.List;

public class ProductOptionExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public ProductOptionExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andOptionValueIdsIsNull() {
			addCriterion("option_value_ids is null");
			return (Criteria) this;
		}

		public Criteria andOptionValueIdsIsNotNull() {
			addCriterion("option_value_ids is not null");
			return (Criteria) this;
		}

		public Criteria andOptionValueIdsEqualTo(String value) {
			addCriterion("option_value_ids =", value, "optionValueIds");
			return (Criteria) this;
		}

		public Criteria andOptionValueIdsNotEqualTo(String value) {
			addCriterion("option_value_ids <>", value, "optionValueIds");
			return (Criteria) this;
		}

		public Criteria andOptionValueIdsGreaterThan(String value) {
			addCriterion("option_value_ids >", value, "optionValueIds");
			return (Criteria) this;
		}

		public Criteria andOptionValueIdsGreaterThanOrEqualTo(String value) {
			addCriterion("option_value_ids >=", value, "optionValueIds");
			return (Criteria) this;
		}

		public Criteria andOptionValueIdsLessThan(String value) {
			addCriterion("option_value_ids <", value, "optionValueIds");
			return (Criteria) this;
		}

		public Criteria andOptionValueIdsLessThanOrEqualTo(String value) {
			addCriterion("option_value_ids <=", value, "optionValueIds");
			return (Criteria) this;
		}

		public Criteria andOptionValueIdsLike(String value) {
			addCriterion("option_value_ids like", value, "optionValueIds");
			return (Criteria) this;
		}

		public Criteria andOptionValueIdsNotLike(String value) {
			addCriterion("option_value_ids not like", value, "optionValueIds");
			return (Criteria) this;
		}

		public Criteria andOptionValueIdsIn(List<String> values) {
			addCriterion("option_value_ids in", values, "optionValueIds");
			return (Criteria) this;
		}

		public Criteria andOptionValueIdsNotIn(List<String> values) {
			addCriterion("option_value_ids not in", values, "optionValueIds");
			return (Criteria) this;
		}

		public Criteria andOptionValueIdsBetween(String value1, String value2) {
			addCriterion("option_value_ids between", value1, value2, "optionValueIds");
			return (Criteria) this;
		}

		public Criteria andOptionValueIdsNotBetween(String value1, String value2) {
			addCriterion("option_value_ids not between", value1, value2, "optionValueIds");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesIsNull() {
			addCriterion("option_value_names is null");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesIsNotNull() {
			addCriterion("option_value_names is not null");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesEqualTo(String value) {
			addCriterion("option_value_names =", value, "optionValueNames");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesNotEqualTo(String value) {
			addCriterion("option_value_names <>", value, "optionValueNames");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesGreaterThan(String value) {
			addCriterion("option_value_names >", value, "optionValueNames");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesGreaterThanOrEqualTo(String value) {
			addCriterion("option_value_names >=", value, "optionValueNames");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesLessThan(String value) {
			addCriterion("option_value_names <", value, "optionValueNames");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesLessThanOrEqualTo(String value) {
			addCriterion("option_value_names <=", value, "optionValueNames");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesLike(String value) {
			addCriterion("option_value_names like", value, "optionValueNames");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesNotLike(String value) {
			addCriterion("option_value_names not like", value, "optionValueNames");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesIn(List<String> values) {
			addCriterion("option_value_names in", values, "optionValueNames");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesNotIn(List<String> values) {
			addCriterion("option_value_names not in", values, "optionValueNames");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesBetween(String value1, String value2) {
			addCriterion("option_value_names between", value1, value2, "optionValueNames");
			return (Criteria) this;
		}

		public Criteria andOptionValueNamesNotBetween(String value1, String value2) {
			addCriterion("option_value_names not between", value1, value2, "optionValueNames");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNull() {
			addCriterion("product_id is null");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNotNull() {
			addCriterion("product_id is not null");
			return (Criteria) this;
		}

		public Criteria andProductIdEqualTo(Integer value) {
			addCriterion("product_id =", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotEqualTo(Integer value) {
			addCriterion("product_id <>", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThan(Integer value) {
			addCriterion("product_id >", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("product_id >=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThan(Integer value) {
			addCriterion("product_id <", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThanOrEqualTo(Integer value) {
			addCriterion("product_id <=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdIn(List<Integer> values) {
			addCriterion("product_id in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotIn(List<Integer> values) {
			addCriterion("product_id not in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdBetween(Integer value1, Integer value2) {
			addCriterion("product_id between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
			addCriterion("product_id not between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andQuantityIsNull() {
			addCriterion("quantity is null");
			return (Criteria) this;
		}

		public Criteria andQuantityIsNotNull() {
			addCriterion("quantity is not null");
			return (Criteria) this;
		}

		public Criteria andQuantityEqualTo(Integer value) {
			addCriterion("quantity =", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityNotEqualTo(Integer value) {
			addCriterion("quantity <>", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityGreaterThan(Integer value) {
			addCriterion("quantity >", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityGreaterThanOrEqualTo(Integer value) {
			addCriterion("quantity >=", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityLessThan(Integer value) {
			addCriterion("quantity <", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityLessThanOrEqualTo(Integer value) {
			addCriterion("quantity <=", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityIn(List<Integer> values) {
			addCriterion("quantity in", values, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityNotIn(List<Integer> values) {
			addCriterion("quantity not in", values, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityBetween(Integer value1, Integer value2) {
			addCriterion("quantity between", value1, value2, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityNotBetween(Integer value1, Integer value2) {
			addCriterion("quantity not between", value1, value2, "quantity");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Integer value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Integer value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Integer value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Integer value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Integer value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Integer> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Integer> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Integer value1, Integer value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table product_option
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_option
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 19 20:55:54 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}